#ifndef EMOSTOOLS_GLOBAL_H
#define EMOSTOOLS_GLOBAL_H

#if defined(EMOSTOOLS_LIBRARY)
#  define EMOSTOOLS_EXPORT Q_DECL_EXPORT
#elif defined(EMOSTOOLS_STATIC_LIBRARY)
#  define EMOSTOOLS_EXPORT
#else
#  define EMOSTOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // EMOSTOOLS_GLOBAL_H
