#ifndef EMOSCODEBUILD_GLOBAL_H
#define EMOSCODEBUILD_GLOBAL_H

#if defined(EMOSCODEBUILD_LIBRARY)
#  define EMOSCODEBUILD_EXPORT Q_DECL_EXPORT
#else
#  define EMOSCODEBUILD_EXPORT Q_DECL_IMPORT
#endif

#endif // EMOSCODEBUILD_GLOBAL_H
