#ifndef DESCRIPTIONEDITOR_GLOBAL_H
#define DESCRIPTIONEDITOR_GLOBAL_H

#if defined(DESCRIPTIONEDITOR_LIBRARY)
#  define DESCRIPTIONEDITOR_EXPORT Q_DECL_EXPORT
#else
#  define DESCRIPTIONEDITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // DESCRIPTIONEDITOR_GLOBAL_H
